apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-pro
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: kubernetes-pro
  server: http://10.132.182.3
  config: |
    {
      "execProviderConfig": {
        "command": "argocd-k8s-auth",
        "args": ["gcp"],
        "apiVersion": "client.authentication.k8s.io/v1beta1"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": "[certificado del cluster encriptado]"
      }
    }